# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "ima"


    filter_sets:
        images_medium:
            filters:
                thumbnail:
                    size: [300,300]
                    mode: outbound
                    upscale: true


        images_small:
            filters:
                thumbnail:
                    size: [200,200]
                    mode: outbound
                    upscale: true 