vich_uploader:
    db_driver: orm

    mappings:
        pin-image:
           uri_prefix: /uploads/pins
           upload_destination: '%kernel.project_dir%/public/uploads/pin'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer